[package]
name = "cowbump"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2021"

[dependencies]
walkdir = "2.3.2"
serde = "1.0.129"
serde_derive = "1.0.129"
rmp-serde = "1.0.0-beta.2"
image = "0.23.14"
lazy_static = "1.4.0"
arboard = "2.0.0"
egui = { git = "https://github.com/emilk/egui.git" }
retain_mut = "0.1.3"
thiserror = "1.0.29"
anyhow = "1.0.44"
fnv = "1.0.7"
directories = "4.0.1"
rfd = "0.5.0"
open = "2.0.1"

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]

[dependencies.egui-sfml]
git = "https://github.com/crumblingstatue/egui-sfml.git"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
