[package]
name = "cowbump"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
failure = "0.1.3"
walkdir = "2.2.6"
serde = "1.0.80"
serde_derive = "1.0.80"
bincode = "1.0.1"
image = "0.20.1"

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]
