[package]
name = "cowbump"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2.3.2"
serde = "1.0.126"
serde_derive = "1.0.126"
bincode = "1.3.3"
image = "0.23.14"
ropey = "1.2.0"
lazy_static = "1.4.0"
arboard = "1.2.1"
atty = "0.2.14"
egui = "0.12.0"
retain_mut = "0.1.3"

[dependencies.sfml]
version = "0.16.0"
default-features = false
features = ["graphics"]

[dependencies.egui-sfml]
git = "https://github.com/crumblingstatue/egui-sfml.git"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
