[package]
name = "cowbump"
version = "0.2.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2021"
default-run = "cowbump"

[dependencies]
walkdir = "2.3.2"
serde = "1.0.130"
serde_derive = "1.0.130"
rmp-serde = "1.0.0-beta.2"
image = "0.23.14"
arboard = "2.0.1"
thiserror = "1.0.30"
anyhow = "1.0.51"
fnv = "1.0.7"
directories = "4.0.1"
rfd = "0.6.1"
open = "2.0.2"
zstd = "0.9.0"
zip = { version = "0.5.13", default-features = false }

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]

[dependencies.egui-sfml]
git = "https://github.com/crumblingstatue/egui-sfml.git"

[dependencies.recently_used_list]
git = "https://github.com/crumblingstatue/recently_used_list.git"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
