[package]
name = "cowbump"
version = "0.2.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2021"
default-run = "cowbump"

[dependencies]
walkdir = "2.3.3"
serde = "1.0.164"
serde_derive = "1.0.164"
rmp-serde = "1.1.1"
image = "0.24.6"
arboard = "3.2.0"
thiserror = "1.0.40"
anyhow = "1.0.71"
fnv = "1.0.7"
directories = "5.0.1"
rfd = "0.11.4"
open = "4.2.0"
zstd = "0.12.3"
zip = { version = "0.6.6", default-features = false }
egui-sfml = {git = "https://github.com/crumblingstatue/egui-sfml.git"}

[dependencies.recently_used_list]
git = "https://github.com/crumblingstatue/recently_used_list.git"

[dependencies.tagfilter-lang]
git = "https://github.com/crumblingstatue/tagfilter-lang.git"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
