[package]
name = "cowbump"
version = "0.2.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2021"
default-run = "cowbump"

[dependencies]
walkdir = "2.3.2"
serde = "1.0.137"
serde_derive = "1.0.137"
rmp-serde = "1.1.0"
image = "0.24.2"
arboard = "2.1.0"
thiserror = "1.0.31"
anyhow = "1.0.57"
fnv = "1.0.7"
directories = "4.0.1"
rfd = "0.8.2"
open = "2.1.2"
zstd = "0.11.2"
zip = { version = "0.6.2", default-features = false }

[dependencies.egui-sfml]
git = "https://github.com/crumblingstatue/egui-sfml.git"

[dependencies.recently_used_list]
git = "https://github.com/crumblingstatue/recently_used_list.git"

[dependencies.tagfilter-lang]
git = "https://github.com/crumblingstatue/tagfilter-lang.git"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
