[package]
name = "cowbump"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.8"
walkdir = "2.3.1"
serde = "1.0.114"
serde_derive = "1.0.114"
bincode = "1.3.1"
image = "0.23.6"
ropey = "1.2.0"

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]
