[package]
name = "cowbump"
version = "0.2.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2021"
default-run = "cowbump"

[dependencies]
walkdir = "2.3.2"
serde = "1.0.147"
serde_derive = "1.0.147"
rmp-serde = "1.1.1"
image = "0.24.5"
arboard = "3.2.0"
thiserror = "1.0.37"
anyhow = "1.0.66"
fnv = "1.0.7"
directories = "4.0.1"
rfd = "0.10.0"
open = "3.0.3"
zstd = "0.11.2"
zip = { version = "0.6.3", default-features = false }
egui-sfml = "0.2.0"

[dependencies.recently_used_list]
git = "https://github.com/crumblingstatue/recently_used_list.git"

[dependencies.tagfilter-lang]
git = "https://github.com/crumblingstatue/tagfilter-lang.git"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
