[package]
name = "cowbump"
version = "0.2.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2021"
default-run = "cowbump"

[dependencies]
walkdir = "2.3.2"
serde = "1.0.152"
serde_derive = "1.0.152"
rmp-serde = "1.1.1"
image = "0.24.5"
arboard = "3.2.0"
thiserror = "1.0.38"
anyhow = "1.0.69"
fnv = "1.0.7"
directories = "4.0.1"
rfd = "0.11.1"
open = "3.2.0"
zstd = "0.12.3"
zip = { version = "0.6.4", default-features = false }
egui-sfml = "0.4.0"

[dependencies.recently_used_list]
git = "https://github.com/crumblingstatue/recently_used_list.git"

[dependencies.tagfilter-lang]
git = "https://github.com/crumblingstatue/tagfilter-lang.git"

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
