[package]
name = "cowbump"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.8"
walkdir = "2.3.1"
serde = "1.0.117"
serde_derive = "1.0.117"
bincode = "1.3.1"
image = "0.23.12"
ropey = "1.2.0"
lazy_static = "1.4.0"
arboard = "1.0.2"
atty = "0.2.14"
egui = "0.9.0"

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2
